spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/globalwindow_test2
    username: root
    password: 5941882333
  data:
    redis:
      host: localhost
      port: 6379
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

mybatis:
  configuration:
    map-underscore-to-camel-case: true



