/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Carousel: typeof import('./src/components/Carousel.vue')['default']
    EarthScene: typeof import('./src/components/earthScene.vue')['default']
    EconomyIcon: typeof import('./src/components/icons/economyIcon.vue')['default']
    MainIcon: typeof import('./src/components/icons/mainIcon.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NButtonGroup: typeof import('naive-ui')['NButtonGroup']
    NCard: typeof import('naive-ui')['NCard']
    NCarousel: typeof import('naive-ui')['NCarousel']
    NEmpty: typeof import('naive-ui')['NEmpty']
    NFlex: typeof import('naive-ui')['NFlex']
    NGrid: typeof import('naive-ui')['NGrid']
    NGridItem: typeof import('naive-ui')['NGridItem']
    NIcon: typeof import('naive-ui')['NIcon']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NMenu: typeof import('naive-ui')['NMenu']
    NResult: typeof import('naive-ui')['NResult']
    NTag: typeof import('naive-ui')['NTag']
    NTags: typeof import('naive-ui')['NTags']
    OtherIcon: typeof import('./src/components/icons/otherIcon.vue')['default']
    PlayIcon: typeof import('./src/components/icons/playIcon.vue')['default']
    PolicyIcon: typeof import('./src/components/icons/policyIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScienceIcon: typeof import('./src/components/icons/scienceIcon.vue')['default']
    WhuIcon: typeof import('./src/components/icons/whuIcon.vue')['default']
  }
}
